linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/peteraba/go-htmx-playground) # Custom section: groups all imports with the specified Prefix.
    #    - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
    #    - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
    custom-order: true
  varnamelen:
    ignore-names:
      - err
      - ok
      - tt
    ignore-decls:
      - idx int
      - i int
      - w *bufio.Writer
      - c *fiber.Ctx
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - .SendStatus(
      - .Redirect(
      - .Render(
      - validate.Struct(
    ignoreSigRegexps:
      - \.New.*Error\(

linters:
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
#  fast: true
  disable:
    # TODO: Check if this is worth enabling
    - depguard
    - lll

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - wsl
    - path: lib/pagination/pagination.go
      linters:
        - gomnd
    - text: should be written without leading space as
      linters:
        - nolintlint
